-   id: dprint
    name: dprint
    description: 'A pluggable and configurable code formatting platform written in Rust.'
    entry: dprint fmt
    language: rust
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["cli:dprint:0.50.0"]
    minimum_pre_commit_version: '0'
